apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-page-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-page
  template:
    metadata:
      labels:
        app: my-web-page
    spec:
      containers:
      - name: my-web-page
        image: yyyyw585/my-web-page:latest
        ports:
        - containerPort: 80
